//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ProviderDateSoap", Namespace = "http://www.ShangHaiGas.org/")]
public partial class ProviderDate : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback GetProviderVersionOperationCompleted;

    private System.Threading.SendOrPostCallback GetProviderFileUrlOperationCompleted;

    private System.Threading.SendOrPostCallback GetChangJiaXMLFileUrlOperationCompleted;

    private System.Threading.SendOrPostCallback GetBiaoChangXXOperationCompleted;

    /// <remarks/>
    public ProviderDate()
    {
        this.Url = "http://212.64.20.54:10086/ProviderDate.asmx";
    }
    public ProviderDate(string _url)
    {
        if (_url != null && _url != string.Empty)
            this.Url = _url;
        else
            this.Url = "http://212.64.20.54:10086/ProviderDate.asmx";
    }

    /// <remarks/>
    public event GetProviderVersionCompletedEventHandler GetProviderVersionCompleted;

    /// <remarks/>
    public event GetProviderFileUrlCompletedEventHandler GetProviderFileUrlCompleted;

    /// <remarks/>
    public event GetChangJiaXMLFileUrlCompletedEventHandler GetChangJiaXMLFileUrlCompleted;

    /// <remarks/>
    public event GetBiaoChangXXCompletedEventHandler GetBiaoChangXXCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ShangHaiGas.org/GetProviderVersion", RequestNamespace = "http://www.ShangHaiGas.org/", ResponseNamespace = "http://www.ShangHaiGas.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetProviderVersion()
    {
        object[] results = this.Invoke("GetProviderVersion", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetProviderVersion(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetProviderVersion", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string EndGetProviderVersion(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void GetProviderVersionAsync()
    {
        this.GetProviderVersionAsync(null);
    }

    /// <remarks/>
    public void GetProviderVersionAsync(object userState)
    {
        if ((this.GetProviderVersionOperationCompleted == null))
        {
            this.GetProviderVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProviderVersionOperationCompleted);
        }
        this.InvokeAsync("GetProviderVersion", new object[0], this.GetProviderVersionOperationCompleted, userState);
    }

    private void OnGetProviderVersionOperationCompleted(object arg)
    {
        if ((this.GetProviderVersionCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProviderVersionCompleted(this, new GetProviderVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ShangHaiGas.org/GetProviderFileUrl", RequestNamespace = "http://www.ShangHaiGas.org/", ResponseNamespace = "http://www.ShangHaiGas.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetProviderFileUrl()
    {
        object[] results = this.Invoke("GetProviderFileUrl", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetProviderFileUrl(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetProviderFileUrl", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string EndGetProviderFileUrl(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void GetProviderFileUrlAsync()
    {
        this.GetProviderFileUrlAsync(null);
    }

    /// <remarks/>
    public void GetProviderFileUrlAsync(object userState)
    {
        if ((this.GetProviderFileUrlOperationCompleted == null))
        {
            this.GetProviderFileUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProviderFileUrlOperationCompleted);
        }
        this.InvokeAsync("GetProviderFileUrl", new object[0], this.GetProviderFileUrlOperationCompleted, userState);
    }

    private void OnGetProviderFileUrlOperationCompleted(object arg)
    {
        if ((this.GetProviderFileUrlCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProviderFileUrlCompleted(this, new GetProviderFileUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ShangHaiGas.org/GetChangJiaXMLFileUrl", RequestNamespace = "http://www.ShangHaiGas.org/", ResponseNamespace = "http://www.ShangHaiGas.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetChangJiaXMLFileUrl()
    {
        object[] results = this.Invoke("GetChangJiaXMLFileUrl", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetChangJiaXMLFileUrl(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetChangJiaXMLFileUrl", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string EndGetChangJiaXMLFileUrl(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void GetChangJiaXMLFileUrlAsync()
    {
        this.GetChangJiaXMLFileUrlAsync(null);
    }

    /// <remarks/>
    public void GetChangJiaXMLFileUrlAsync(object userState)
    {
        if ((this.GetChangJiaXMLFileUrlOperationCompleted == null))
        {
            this.GetChangJiaXMLFileUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChangJiaXMLFileUrlOperationCompleted);
        }
        this.InvokeAsync("GetChangJiaXMLFileUrl", new object[0], this.GetChangJiaXMLFileUrlOperationCompleted, userState);
    }

    private void OnGetChangJiaXMLFileUrlOperationCompleted(object arg)
    {
        if ((this.GetChangJiaXMLFileUrlCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetChangJiaXMLFileUrlCompleted(this, new GetChangJiaXMLFileUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ShangHaiGas.org/GetBiaoChangXX", RequestNamespace = "http://www.ShangHaiGas.org/", ResponseNamespace = "http://www.ShangHaiGas.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetBiaoChangXX()
    {
        object[] results = this.Invoke("GetBiaoChangXX", new object[0]);
        return ((System.Data.DataTable)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetBiaoChangXX(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetBiaoChangXX", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public System.Data.DataTable EndGetBiaoChangXX(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }

    /// <remarks/>
    public void GetBiaoChangXXAsync()
    {
        this.GetBiaoChangXXAsync(null);
    }

    /// <remarks/>
    public void GetBiaoChangXXAsync(object userState)
    {
        if ((this.GetBiaoChangXXOperationCompleted == null))
        {
            this.GetBiaoChangXXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBiaoChangXXOperationCompleted);
        }
        this.InvokeAsync("GetBiaoChangXX", new object[0], this.GetBiaoChangXXOperationCompleted, userState);
    }

    private void OnGetBiaoChangXXOperationCompleted(object arg)
    {
        if ((this.GetBiaoChangXXCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetBiaoChangXXCompleted(this, new GetBiaoChangXXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetProviderVersionCompletedEventHandler(object sender, GetProviderVersionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProviderVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetProviderVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetProviderFileUrlCompletedEventHandler(object sender, GetProviderFileUrlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProviderFileUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetProviderFileUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetChangJiaXMLFileUrlCompletedEventHandler(object sender, GetChangJiaXMLFileUrlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetChangJiaXMLFileUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetChangJiaXMLFileUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetBiaoChangXXCompletedEventHandler(object sender, GetBiaoChangXXCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetBiaoChangXXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetBiaoChangXXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public System.Data.DataTable Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}
