//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.8.3928.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MessageDataServiceSoap", Namespace="http://www.shanghai3h.com/")]
public partial class MessageDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTX_MessageDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateTX_MessageDataOperationCompleted;
    
    /// <remarks/>
    public MessageDataService() {
        this.Url = "http://172.30.0.189:8669/MessageDataService.asmx";
    }
    public MessageDataService(string _url)
    {
        if (_url != "")
        {
            base.Url = _url;
        }
        else
        {
            base.Url = "http://172.30.0.189:8669/MessageDataService.asmx";
        }
    }
    
    /// <remarks/>
    public event GetTX_MessageDataCompletedEventHandler GetTX_MessageDataCompleted;
    
    /// <remarks/>
    public event UpdateTX_MessageDataCompletedEventHandler UpdateTX_MessageDataCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.shanghai3h.com/HelloWorld", RequestNamespace="http://www.shanghai3h.com/", ResponseNamespace="http://www.shanghai3h.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
   
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.shanghai3h.com/GetTX_MessageData", RequestNamespace="http://www.shanghai3h.com/", ResponseNamespace="http://www.shanghai3h.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetTX_MessageData(int I_FASONGLX, int I_FASONGZT) {
        object[] results = this.Invoke("GetTX_MessageData", new object[] {
                    I_FASONGLX,
                    I_FASONGZT});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTX_MessageData(int I_FASONGLX, int I_FASONGZT, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTX_MessageData", new object[] {
                    I_FASONGLX,
                    I_FASONGZT}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetTX_MessageData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetTX_MessageDataAsync(int I_FASONGLX, int I_FASONGZT) {
        this.GetTX_MessageDataAsync(I_FASONGLX, I_FASONGZT, null);
    }
    
    /// <remarks/>
    public void GetTX_MessageDataAsync(int I_FASONGLX, int I_FASONGZT, object userState) {
        if ((this.GetTX_MessageDataOperationCompleted == null)) {
            this.GetTX_MessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTX_MessageDataOperationCompleted);
        }
        this.InvokeAsync("GetTX_MessageData", new object[] {
                    I_FASONGLX,
                    I_FASONGZT}, this.GetTX_MessageDataOperationCompleted, userState);
    }
    
    private void OnGetTX_MessageDataOperationCompleted(object arg) {
        if ((this.GetTX_MessageDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTX_MessageDataCompleted(this, new GetTX_MessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.shanghai3h.com/UpdateTX_MessageData", RequestNamespace="http://www.shanghai3h.com/", ResponseNamespace="http://www.shanghai3h.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool UpdateTX_MessageData(int JLID, int I_FASONGLX, int I_FASONGZT, string S_HuiFu) {
        object[] results = this.Invoke("UpdateTX_MessageData", new object[] {
                    JLID,
                    I_FASONGLX,
                    I_FASONGZT,
                    S_HuiFu});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateTX_MessageData(int JLID, int I_FASONGLX, int I_FASONGZT, string S_HuiFu, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateTX_MessageData", new object[] {
                    JLID,
                    I_FASONGLX,
                    I_FASONGZT,
                    S_HuiFu}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndUpdateTX_MessageData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateTX_MessageDataAsync(int JLID, int I_FASONGLX, int I_FASONGZT, string S_HuiFu) {
        this.UpdateTX_MessageDataAsync(JLID, I_FASONGLX, I_FASONGZT, S_HuiFu, null);
    }
    
    /// <remarks/>
    public void UpdateTX_MessageDataAsync(int JLID, int I_FASONGLX, int I_FASONGZT, string S_HuiFu, object userState) {
        if ((this.UpdateTX_MessageDataOperationCompleted == null)) {
            this.UpdateTX_MessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTX_MessageDataOperationCompleted);
        }
        this.InvokeAsync("UpdateTX_MessageData", new object[] {
                    JLID,
                    I_FASONGLX,
                    I_FASONGZT,
                    S_HuiFu}, this.UpdateTX_MessageDataOperationCompleted, userState);
    }
    
    private void OnUpdateTX_MessageDataOperationCompleted(object arg) {
        if ((this.UpdateTX_MessageDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateTX_MessageDataCompleted(this, new UpdateTX_MessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetTX_MessageDataCompletedEventHandler(object sender, GetTX_MessageDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTX_MessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTX_MessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void UpdateTX_MessageDataCompletedEventHandler(object sender, UpdateTX_MessageDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateTX_MessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateTX_MessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
